# Generated by Django 4.2.14 on 2024-07-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_active',
            new_name='is_activated',
        ),
    ]
