# Generated by Django 4.2.14 on 2024-07-13 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_confirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
